### ISSUE TITLE
required attribute to be an array of "filter" in validateBody function

### ISSUE THREAD

**Issue by wmehanna** [srinivasiyer/koa-validation#1]
I would like to know if it's possible to to force an attribute to be an array of string with a regex.

What i'm trying to achieve is to have an attribute "phone : []" and each data in the array needs to be validated to have a specific format using a regex.

**Comment by srinivasiyer** [comment]
Hi Wassim,

There is no built in rule that provides for your requirement. However, you can extend the Rules class to achieve the same. Now if you can answer a couple of my questions, I could help you out.
1. Do you want all the values in the array to have the same regex rule?
2. If so what regex do you wish to apply?

If you can get back to me with the same, I can help you write a custom rule which could handle your situation easily.

**Comment by wmehanna** [comment]
Hello Srinivas,

Thank you for you're kind reply!
1. Yes that's what I'm looking for
2. Here's the regex that validates phone numbers : ^([0-9()\/+ -]*)$

Thank you !

On Tue, Jan 12, 2016 at 4:33 PM, Srinivas Iyer notifications@github.com
wrote:

> Hi Wassim,
> 
> There is no built in rule that provides for your requirement. However, you
> can extend the Rules class to achieve the same. Now if you can answer a
> couple of my questions, I could help you out.
> 1. Do you want all the values in the array to have the same regex rule?
> 2. If so what regex do you wish to apply?
> 
> If you can get back to me with the same, I can help you write a custom
> rule which could handle your situation easily.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/srinivasiyer/koa-validation/issues/1#issuecomment-171064271
> .

## 

_Wassim Mehanna_
Consultant T.I | WM Solutions inc.
Cellulaire : 514-576-6183

**Comment by srinivasiyer** [comment]
Hi Wassim,

Apologies for the late response. Unfortunately, I got a pit tied up. Check the code below and let me know if it serves your need.

``` javascript
'use strict';

const app = require('koa')();
const koaBody = require('koa-better-body');

let validate = require('koa-validation');

app.use(koaBody({
    'multipart': true
}));

//Field Rules Class
let Rules = validate.Rules;

Rules.prototype.arrayWithRegex = function *(field, value, regexp, message){
    if(regexp instanceof RegExp){
        if(typeof value === 'object' && Array.isArray(value)){
            if(value.length){
                let valid = true;
                for(let i = 0; i < value.length; ++i){
                    if(regexp.test(value[i]) === false) {
                        valid = false;
                        this.validator.addError(field, 'rule', 'arrayWithRegex', message || 'Invalid Match Found in the array sent')
                        break;
                    }
                }

                return valid;
            }else{
                this.validator.addError(field, 'rule', 'arrayWithRegex', message || 'The field value cannot be an empty array')
                return false;
            }
        }else{
            this.validator.addError(field, 'rule', 'arrayWithRegex', message || 'The value of the field needs to be an array');
            return false;
        }
    }else{
        this.validator.addError(field, 'rule', 'arrayWithRegex', message || 'The regex arguement is not a valid regular expression');
        return false;
    }
}

app.use(validate());

app.use(function *(){

    yield this.validateBody({
        phone_numbers: { arrayWithRegex: [/^([0-9\(\)\/\+ \-]*)$/] },
    });

    if (this.validationErrors) {
        this.status = 422;
        this.body = this.validationErrors;
    } else {
        this.status = 200;
        this.body = { success: true }
    }
});

app.listen(3000);
```

The above validation allows you to have an array and each element being validated with the regex specified in the argument. This would work not only for your specific regex, but any regex which you can change dynamically. Let me know if it worked for you

**Comment by wmehanna** [comment]
Thanks a lot for that it worked perfectly fine!.

You'r code also gave me the opportunity to understand how to extend a module with a and existing module .  

I got a new question; sorry if it has been answered in you'r readme.io docs but I was not able to find it.  Is it possible to accept only n attributes and reject all others ?

example : 
{
    "lastName" : "titi",
    "firstName" : "toto",
    "email" : "titi@toto.com",
    "phone" : ["555-555-5555", "111-111-1111"],
    "brand" : "22"
}

This body would fail because it has other attributes than "lastName, firstName, email, phone".  The attribute "brand" would be the cause in this case.

Thank you

**Comment by srinivasiyer** [comment]
I did not understand the question properly. Do you mind re-explaining??

**Comment by wmehanna** [comment]
Simply,

I want to accept a certain number of attributes and refuse if there's any
other on a post method.

Example : a post method containing this json in the body having the
following { "name" : "Familly name", "firstName" :"A first Name"} would
return a 201 status.
But a json with the following { "name" : "Familly name", "firstName" :"A
first Name", "sex" : "Male"} would be refused because the "sex" should not
be in the json.

On Sun, Jan 17, 2016 at 11:41 AM, Srinivas Iyer notifications@github.com
wrote:

> I did not understand the question properly. Do you mind re-explaining??
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/srinivasiyer/koa-validation/issues/1#issuecomment-172348227
> .

## 

_Wassim Mehanna_
Consultant T.I | WM Solutions inc.
Cellulaire : 514-576-6183

**Comment by srinivasiyer** [comment]
You can have as many fields as you want. Only field you are looking to validate will have rules applied to them. Any other fields will not create a problem.

So basically, you can have as many fields as you wish for and not validate them if thats your requirement

**Comment by srinivasiyer** [comment]
You can have as many fields as you want. Only field you are looking to validate will have rules applied to them. Any other fields will not create a problem.

So basically, you can have as many fields as you wish for and not validate them if thats your requirement

**Comment by wmehanna** [comment]
Perfect !
You'r explanation answers my question.  Thank you again for everything!
